# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.TextField()),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('short_desc', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
