# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-26 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='skype',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Skype'),
        ),
    ]
