# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-17 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160826_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostProxy',
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
